version: '3.5'
services:
  front:
    container_name: front
    restart: always
    image: node:16
    working_dir: /app
    command: sh -c "npm rebuild esbuild && npm run dev"
    ports:
      - '3004:3004'
    volumes:
      - ./:/app
